services:
  front:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: npm run dev
    restart: always
  api:
    build: ./backend
    container_name: chat_api
    ports:
      - "5000:5000"