services:
  api:
    image: node:20-alpine
    container_name: node-api-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app              # mount mã nguồn
      - /app/node_modules  # tránh node_modules bị đè bởi bind mount
    command: sh -c "npm ci && npm run dev"
    environment:
      - PORT=3000
