services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chat_rabbitmq
    ports:
      - "5672:5672" # AMQP Protocol
      - "15672:15672" # Management UI
    restart: always

  redis:
    image: redis:alpine
    container_name: chat_redis
    ports:
      - "6379:6379"
    restart: always

  database:
    image: mongo:latest
    container_name: chat_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatuser
      MONGO_INITDB_ROOT_PASSWORD: chatpassword
    restart: always

  backend:
    build: ./backend
    command: npm start
    environment:
      MONGO_URI: "mongodb://chatuser:chatpassword@database:27017/chat_db?authSource=admin"
      PORT: 5000
      RABBITMQ_URL: "amqp://rabbitmq:5672"
      REDIS_URL : "redis://redis:6379"
    depends_on:
      - database
      - rabbitmq
      - redis
    restart: always
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    container_name: chat_nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always

  front:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    environment:
      # VITE_API_URL: http://localhost:5000
      VITE_API_URL: http://host.docker.internal:5000
    restart: always

volumes:
  mongo_data:
  redis_data:
